version: "3.8"

services:
  app: &rails
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:hi@db:5432
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./home:/home/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
  webpacker:
    <<: *rails
    command: webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: hi
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  bundle:
  node_modules:
  pgdata:
