version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:hi@db:5432
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./home:/home/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: hi
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  bundle:
  node_modules:
  pgdata:
